import ArticlesView from "@/views/Articles";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Math Articles, Essays & Academic Publications",
  description: "Browse academic publications, student-written logs, math theories, historical breakthroughs, and olympiad guidelines published by Josephite Math Club members.",
  keywords: [
    "Math Articles BD",
    "Josephite Academic Publications",
    "JMC Mathematical Journal",
    "Olympiad Preparation Essays",
    "High School Mathematics Research Papers",
    "St. Joseph Student Writing",
  ],
  alternates: {
    canonical: "/articles",
  },
  openGraph: {
    title: "Math Articles, Essays & Academic Publications | Josephite Math Club",
    description: "Read peer-contributed mathematical articles, elegant calculus derivations, number theory explanations, and research work generated by SJS student members.",
    url: "https://jmc-sjs.org/articles",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "JMC Academic Publications & Articles",
    description: "Browse advanced mathematical essays, proof discussions, and articles written by members of the Josephite Math Club.",
  },
};

export default function ArticlesPage() {
  const articlesIndexJsonLd = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebPage",
        "@id": "https://jmc-sjs.org/articles#webpage",
        "url": "https://jmc-sjs.org/articles",
        "name": "Math Articles, Essays & Academic Publications",
        "description": "An educational repository containing academic essays, geometry breakdowns, calculus research, and training articles from the SJS student body.",
        "isPartOf": {
          "@id": "https://jmc-sjs.org/#website"
        },
        "breadcrumb": {
          "@id": "https://jmc-sjs.org/articles#breadcrumb"
        }
      },
      {
        "@type": "BreadcrumbList",
        "@id": "https://jmc-sjs.org/articles#breadcrumb",
        "itemListElement": [
          {
            "@type": "ListItem",
            "position": 1,
            "name": "Home",
            "item": "https://jmc-sjs.org"
          },
          {
            "@type": "ListItem",
            "position": 2,
            "name": "Articles",
            "item": "https://jmc-sjs.org/articles"
          }
        ]
      }
    ]
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(articlesIndexJsonLd) }}
      />
      <ArticlesView />
    </>
  );
}

